//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hadeel_0523077_w4
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UsID { get; set; }
        public string UName { get; set; }
        public string Upass { get; set; }
        public string UEmail { get; set; }
        public string Urole { get; set; }
        public Nullable<int> taskID { get; set; }
    
        public virtual task task { get; set; }
    }
}
